import profileArmenBaldryan from "../../images/ArmenBaldryan/profile.jpg";
import profileArmenBaldryan2 from "../../images/ArmenBaldryan/1.jpg";

import araikProfile from "../../images/Araik/profile.jpg";
import araik1 from "../../images/Araik/1.jpg";

import armenVahagniProfile from "../../images/ArmenVahagni/profile.jpg";
import armenVahagni1 from "../../images/ArmenVahagni/a.jpg";

import manvelProfile from "../../images/Manvel/profile.jpg";
import manvel1 from "../../images/Manvel/1.jpg";

export interface NewDataProps {
    id: number;
    title: string;
    subtitle: string;
    description: string;
    date: string | Date;
    client?: string;
    address?: string;
    architect?: string;
    area?: string;
    stage?: string;
    profileImage: string;
    images: string[];
}

export interface CategoryData {
    id: number;
    name: string;
    title: string;
    link: string;
    description?: string;
    projects: NewDataProps[];
}

export const residentialCategoryData: CategoryData = {
    id: 1,
    name: "residential",
    title: "Residential Projects",
    link: "residential-projects",
    description: "Projects designed for living spaces.",
    projects: [
        {
            id: 1,
            title: "Modern Villa",
            subtitle: "Contemporary Design",
            description: "A contemporary residential villa project.",
            date: "2023-08-12",
            client: "Smith Family",
            address: "123 Maple Street, Springfield",
            architect: "John Doe",
            area: "3500 sq ft",
            stage: "Completed",
            profileImage: araikProfile,
            images: [araikProfile, araik1],
        },
        {
            id: 2,
            title: "Luxury Apartment",
            subtitle: "High-rise Living",
            description: "High-rise luxury apartment complex.",
            date: "2022-05-18",
            client: "Green Properties",
            address: "456 Oak Avenue, Riverdale",
            architect: "Jane Smith",
            area: "5000 sq ft",
            stage: "In Progress",
            profileImage: armenVahagniProfile,
            images: [armenVahagniProfile, armenVahagni1],
        },
        {
            id: 3,
            title: "Eco-Friendly House",
            subtitle: "Sustainable Living",
            description: "Sustainable house with green technologies.",
            date: "2021-11-02",
            client: "Eco Homes Inc.",
            address: "789 Pine Road, Greenfield",
            architect: "Eco Architect",
            area: "2500 sq ft",
            stage: "Planning",
            profileImage: profileArmenBaldryan,
            images: [profileArmenBaldryan, profileArmenBaldryan2],
        },
        {
            id: 4,
            title: "Beachfront Bungalow",
            subtitle: "Coastal Charm",
            description: "Charming bungalow by the beach.",
            date: "2020-07-15",
            client: "Coastal Living",
            address: "321 Ocean Drive, Beach City",
            architect: "Coastal Architects",
            area: "1800 sq ft",
            stage: "Completed",
            profileImage: manvelProfile,
            images: [manvelProfile, manvel1],
        },
        {
            id: 1,
            title: "Modern Villa",
            subtitle: "Contemporary Design",
            description: "A contemporary residential villa project.",
            date: "2023-08-12",
            client: "Smith Family",
            address: "123 Maple Street, Springfield",
            architect: "John Doe",
            area: "3500 sq ft",
            stage: "Completed",
            profileImage: araikProfile,
            images: [araikProfile, araik1],
        },
        {
            id: 2,
            title: "Luxury Apartment",
            subtitle: "High-rise Living",
            description: "High-rise luxury apartment complex.",
            date: "2022-05-18",
            client: "Green Properties",
            address: "456 Oak Avenue, Riverdale",
            architect: "Jane Smith",
            area: "5000 sq ft",
            stage: "In Progress",
            profileImage: armenVahagniProfile,
            images: [armenVahagniProfile, armenVahagni1],
        },
        {
            id: 3,
            title: "Eco-Friendly House",
            subtitle: "Sustainable Living",
            description: "Sustainable house with green technologies.",
            date: "2021-11-02",
            client: "Eco Homes Inc.",
            address: "789 Pine Road, Greenfield",
            architect: "Eco Architect",
            area: "2500 sq ft",
            stage: "Planning",
            profileImage: profileArmenBaldryan,
            images: [profileArmenBaldryan, profileArmenBaldryan2],
        },
        {
            id: 4,
            title: "Beachfront Bungalow",
            subtitle: "Coastal Charm",
            description: "Charming bungalow by the beach.",
            date: "2020-07-15",
            client: "Coastal Living",
            address: "321 Ocean Drive, Beach City",
            architect: "Coastal Architects",
            area: "1800 sq ft",
            stage: "Completed",
            profileImage: manvelProfile,
            images: [manvelProfile, manvel1],
        },
        {
            id: 1,
            title: "Modern Villa",
            subtitle: "Contemporary Design",
            description: "A contemporary residential villa project.",
            date: "2023-08-12",
            client: "Smith Family",
            address: "123 Maple Street, Springfield",
            architect: "John Doe",
            area: "3500 sq ft",
            stage: "Completed",
            profileImage: araikProfile,
            images: [araikProfile, araik1],
        },
        {
            id: 2,
            title: "Luxury Apartment",
            subtitle: "High-rise Living",
            description: "High-rise luxury apartment complex.",
            date: "2022-05-18",
            client: "Green Properties",
            address: "456 Oak Avenue, Riverdale",
            architect: "Jane Smith",
            area: "5000 sq ft",
            stage: "In Progress",
            profileImage: armenVahagniProfile,
            images: [armenVahagniProfile, armenVahagni1],
        },
        {
            id: 3,
            title: "Eco-Friendly House",
            subtitle: "Sustainable Living",
            description: "Sustainable house with green technologies.",
            date: "2021-11-02",
            client: "Eco Homes Inc.",
            address: "789 Pine Road, Greenfield",
            architect: "Eco Architect",
            area: "2500 sq ft",
            stage: "Planning",
            profileImage: profileArmenBaldryan,
            images: [profileArmenBaldryan, profileArmenBaldryan2],
        },
        {
            id: 4,
            title: "Beachfront Bungalow",
            subtitle: "Coastal Charm",
            description: "Charming bungalow by the beach.",
            date: "2020-07-15",
            client: "Coastal Living",
            address: "321 Ocean Drive, Beach City",
            architect: "Coastal Architects",
            area: "1800 sq ft",
            stage: "Completed",
            profileImage: manvelProfile,
            images: [manvelProfile, manvel1],
        },
        {
            id: 1,
            title: "Modern Villa",
            subtitle: "Contemporary Design",
            description: "A contemporary residential villa project.",
            date: "2023-08-12",
            client: "Smith Family",
            address: "123 Maple Street, Springfield",
            architect: "John Doe",
            area: "3500 sq ft",
            stage: "Completed",
            profileImage: araikProfile,
            images: [araikProfile, araik1],
        },
        {
            id: 2,
            title: "Luxury Apartment",
            subtitle: "High-rise Living",
            description: "High-rise luxury apartment complex.",
            date: "2022-05-18",
            client: "Green Properties",
            address: "456 Oak Avenue, Riverdale",
            architect: "Jane Smith",
            area: "5000 sq ft",
            stage: "In Progress",
            profileImage: armenVahagniProfile,
            images: [armenVahagniProfile, armenVahagni1],
        },
        {
            id: 3,
            title: "Eco-Friendly House",
            subtitle: "Sustainable Living",
            description: "Sustainable house with green technologies.",
            date: "2021-11-02",
            client: "Eco Homes Inc.",
            address: "789 Pine Road, Greenfield",
            architect: "Eco Architect",
            area: "2500 sq ft",
            stage: "Planning",
            profileImage: profileArmenBaldryan,
            images: [profileArmenBaldryan, profileArmenBaldryan2],
        },
        {
            id: 4,
            title: "Beachfront Bungalow",
            subtitle: "Coastal Charm",
            description: "Charming bungalow by the beach.",
            date: "2020-07-15",
            client: "Coastal Living",
            address: "321 Ocean Drive, Beach City",
            architect: "Coastal Architects",
            area: "1800 sq ft",
            stage: "Completed",
            profileImage: manvelProfile,
            images: [manvelProfile, manvel1],
        },
    ],
};

export const commercialCategoryData: CategoryData = {
    id: 2,
    name: "commercial",
    title: "Commercial Projects",
    link: "commercial-projects",
    description: "Buildings and infrastructure for businesses.",
    projects: [
        {
            id: 5,
            title: "Tech Office Building",
            subtitle: "Innovative Workspace",
            description: "State-of-the-art office space for a tech company.",
            date: "2021-11-02",
            client: "Innovatech",
            address: "789 Silicon Blvd, San Francisco",
            architect: "Tech Architects Inc.",
            area: "10000 sq ft",
            stage: "Completed",
            profileImage: "/images/office1.jpg",
            images: ["/images/office1.jpg", "/images/office2.jpg"],
        },
        {
            id: 6,
            title: "Shopping Mall",
            subtitle: "Retail Paradise",
            description: "Large shopping complex with various stores.",
            date: "2020-07-15",
            client: "City Mall Group",
            address: "321 Commerce St, Metropolis",
            architect: "Retail Design Co.",
            area: "50000 sq ft",
            stage: "Completed",
            profileImage: "/images/mall1.jpg",
            images: ["/images/mall1.jpg", "/images/mall2.jpg"],
        },
        {
            id: 7,
            title: "Corporate Headquarters",
            subtitle: "Modern Business Hub",
            description: "Headquarters for a multinational corporation.",
            date: "2022-05-18",
            client: "Global Corp",
            address: "456 Business Rd, Capital City",
            architect: "Corporate Architects Ltd.",
            area: "20000 sq ft",
            stage: "In Progress",
            profileImage: "/images/corporate1.jpg",
            images: ["/images/corporate1.jpg", "/images/corporate2.jpg"],
        },
        {
            id: 8,
            title: "Restaurant Design",
            subtitle: "Culinary Experience",
            description: "Unique design for a fine dining restaurant.",
            date: "2023-08-12",
            client: "Gourmet Eats",
            address: "123 Culinary Ave, Food City",
            architect: "Culinary Architects",
            area: "3000 sq ft",
            stage: "Completed",
            profileImage: "/images/restaurant1.jpg",
            images: ["/images/restaurant1.jpg", "/images/restaurant2.jpg"],
        },
    ],
};

export const industrialCategoryData: CategoryData = {
    id: 3,
    name: "industrial",
    title: "Industrial Projects",
    link: "industrial-projects",
    description: "Infrastructure and facilities for industries.",
    projects: [
        {
            id: 9,
            title: "Manufacturing Plant",
            subtitle: "Production Facility",
            description: "Large-scale manufacturing plant.",
            date: "2021-11-02",
            client: "Industry Leaders Inc.",
            address: "789 Factory Rd, Industrial Park",
            architect: "Industrial Design Group",
            area: "50000 sq ft",
            stage: "Completed",
            profileImage: "/images/plant1.jpg",
            images: ["/images/plant1.jpg", "/images/plant2.jpg"],
        },
        {
            id: 10,
            title: "Warehouse Complex",
            subtitle: "Storage Solutions",
            description: "Modern warehouse complex for logistics.",
            date: "2020-07-15",
            client: "Logistics Co.",
            address: "321 Storage St, Warehouse City",
            architect: "Warehouse Architects",
            area: "30000 sq ft",
            stage: "In Progress",
            profileImage: "/images/warehouse1.jpg",
            images: ["/images/warehouse1.jpg", "/images/warehouse2.jpg"],
        },
        {
            id: 11,
            title: "Distribution Center",
            subtitle: "Logistics Hub",
            description: "Central hub for distribution and logistics.",
            date: "2022-05-18",
            client: "Distribution Solutions",
            address: "456 Logistics Ave, Supply City",
            architect: "Logistics Architects",
            area: "40000 sq ft",
            stage: "Completed",
            profileImage: "/images/distribution1.jpg",
            images: ["/images/distribution1.jpg", "/images/distribution2.jpg"],
        },
        {
            id: 12,
            title: "Power Plant",
            subtitle: "Energy Generation",
            description: "Facility for energy generation.",
            date: "2023-08-12",
            client: "Energy Corp",
            address: "123 Energy Rd, Power City",
            architect: "Energy Architects",
            area: "60000 sq ft",
            stage: "Planning",
            profileImage: "/images/powerplant1.jpg",
            images: ["/images/powerplant1.jpg", "/images/powerplant2.jpg"],
        },
    ],
};

    export const urbanCategoryData: CategoryData = {
        id: 4,
        name: "urban",
        title: "Urban Projects",
        link: "urban-projects",
        description: "Projects focused on urban development and planning.",
        projects: [
            {
                id: 13,
                title: "City Park",
                subtitle: "Green Oasis",
                description: "A large park in the heart of the city.",
                date: "2022-03-15",
                client: "City Council",
                address: "Central Park Ave, Urban City",
                architect: "Urban Landscapes Inc.",
                area: "100 acres",
                stage: "Completed",
                profileImage: "/images/park1.jpg",
                images: ["/images/park1.jpg", "/images/park2.jpg"],
            },
            {
                id: 14,
                title: "Urban Plaza",
                subtitle: "Community Space",
                description: "A vibrant plaza for community gatherings.",
                date: "2021-09-10",
                client: "Urban Development Authority",
                address: "Main Square, Downtown",
                architect: "Plaza Designers Ltd.",
                area: "50,000 sq ft",
                stage: "In Progress",
                profileImage: "/images/plaza1.jpg",
                images: ["/images/plaza1.jpg", "/images/plaza2.jpg"],
            },
            {
                id: 15,
                title: "Public Library",
                subtitle: "Knowledge Hub",
                description: "A modern library for the urban population.",
                date: "2020-06-20",
                client: "City Library Board",
                address: "Library Lane, Knowledge District",
                architect: "Library Architects Co.",
                area: "25,000 sq ft",
                stage: "Completed",
                profileImage: "/images/library1.jpg",
                images: ["/images/library1.jpg", "/images/library2.jpg"],
            },
            {
                id: 16,
                title: "Transportation Hub",
                subtitle: "Connecting the City",
                description: "A central hub for urban transportation.",
                date: "2023-01-05",
                client: "City Transit Authority",
                address: "Transit Blvd, Urban Center",
                architect: "Transit Designers Group",
                area: "150,000 sq ft",
                stage: "Planning",
                profileImage: "/images/transport1.jpg",
                images: ["/images/transport1.jpg", "/images/transport2.jpg"],
            },
        ],
    };

    export const reconstructionCategoryData: CategoryData = {
        id: 5,
        name: "reconstruction",
        title: "Reconstruction Projects",
        link: "reconstruction-projects",
        description: "Projects focused on rebuilding and restoring structures.",
        projects: [
            {
                id: 17,
                title: "Historic Building Restoration",
                subtitle: "Preserving Heritage",
                description: "Restoration of a historic building to its former glory.",
                date: "2021-04-10",
                client: "Heritage Society",
                address: "Old Town Square, Heritage City",
                architect: "Historic Architects Inc.",
                area: "15,000 sq ft",
                stage: "Completed",
                profileImage: "/images/historic1.jpg",
                images: ["/images/historic1.jpg", "/images/historic2.jpg"],
            },
            {
                id: 18,
                title: "Bridge Reconstruction",
                subtitle: "Infrastructure Renewal",
                description: "Reconstruction of an old bridge for modern use.",
                date: "2022-08-25",
                client: "City Infrastructure Dept.",
                address: "River Crossing, Bridge City",
                architect: "Bridge Builders Co.",
                area: "N/A",
                stage: "In Progress",
                profileImage: "/images/bridge1.jpg",
                images: ["/images/bridge1.jpg", "/images/bridge2.jpg"],
            },
            {
                id: 19,
                title: "School Renovation",
                subtitle: "Modern Learning Spaces",
                description: "Renovation of an old school building.",
                date: "2020-11-15",
                client: "Education Board",
                address: "123 Learning St, Education City",
                architect: "School Designers Ltd.",
                area: "20,000 sq ft",
                stage: "Completed",
                profileImage: "/images/school1.jpg",
                images: ["/images/school1.jpg", "/images/school2.jpg"],
            },
            {
                id: 20,
                title: "Church Restoration",
                subtitle: "Spiritual Renewal",
                description: "Restoration of a historic church.",
                date: "2023-02-10",
                client: "Church Committee",
                address: "456 Faith Rd, Spiritual Town",
                architect: "Sacred Architects",
                area: "10,000 sq ft",
                stage: "Planning",
                profileImage: "/images/church1.jpg",
                images: ["/images/church1.jpg", "/images/church2.jpg"],
            },
        ],
    };

    export const smallCategoryData: CategoryData = {
        id: 6,
        name: "small",
        title: "Small Projects",
        link: "small-projects",
        description: "Smaller scale projects with unique designs.",
        projects: [
            {
                id: 21,
                title: "Tiny House",
                subtitle: "Compact Living",
                description: "A small, efficient, and stylish tiny house.",
                date: "2021-06-10",
                client: "Minimalist Living",
                address: "789 Cozy Lane, Smallville",
                architect: "Tiny Home Designers",
                area: "500 sq ft",
                stage: "Completed",
                profileImage: "/images/tinyhouse1.jpg",
                images: ["/images/tinyhouse1.jpg", "/images/tinyhouse2.jpg"],
            },
            {
                id: 22,
                title: "Garden Shed",
                subtitle: "Backyard Utility",
                description: "A functional and aesthetic garden shed.",
                date: "2022-09-05",
                client: "Green Thumb",
                address: "123 Garden Path, Bloom City",
                architect: "Shed Builders Co.",
                area: "200 sq ft",
                stage: "In Progress",
                profileImage: "/images/shed1.jpg",
                images: ["/images/shed1.jpg", "/images/shed2.jpg"],
            },
            {
                id: 23,
                title: "Home Office Pod",
                subtitle: "Work from Home",
                description: "A standalone pod for a home office.",
                date: "2020-12-20",
                client: "Remote Work Solutions",
                address: "456 Productivity Ave, Worktown",
                architect: "Pod Designers Ltd.",
                area: "150 sq ft",
                stage: "Completed",
                profileImage: "/images/officepod1.jpg",
                images: ["/images/officepod1.jpg", "/images/officepod2.jpg"],
            },
            {
                id: 24,
                title: "Playhouse",
                subtitle: "Kids' Paradise",
                description: "A fun and safe playhouse for children.",
                date: "2023-03-15",
                client: "Happy Kids",
                address: "789 Fun St, Play City",
                architect: "Playhouse Architects",
                area: "300 sq ft",
                stage: "Planning",
                profileImage: "/images/playhouse1.jpg",
                images: ["/images/playhouse1.jpg", "/images/playhouse2.jpg"],
            },
        ],
    };


export const categoryDataArray = [
    residentialCategoryData,
    commercialCategoryData,
    industrialCategoryData,
    urbanCategoryData,
    reconstructionCategoryData,
    smallCategoryData,
];



